POST http://localhost:4005/app/signupteach
Content-Type: application/json

{
    "fullName": "Nishad",
    "username": "nish",
    "stream" : "nish@gmail.com",
    "batch" : "new",
    "password" : "Basin@123"
}